{
 "title": "ghnotify",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, code) (rate(ghnotify_http_response_duration_seconds_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Change in Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "deriv(\n  histogram_quantile(0.95, sum by(le, code) (rate(ghnotify_http_response_duration_seconds_bucket[$__rate_interval])))[$__rate_interval:])\n"
    }
   ]
  },
  { "title": "ghnotify", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Number of 500 errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(ghnotify_http_status_total{code=\"500\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Change in 500 rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "deriv(rate(ghnotify_http_status_total{code=\"500\",job=\"ghnotify\"}[$__rate_interval])[5m:])\n"
    }
   ]
  },
  { "title": "OPA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Ratio of Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_count{handler=\"v1/data\", method=\"post\"}[$__rate_interval])) by (code)\n) \n/\nscalar(\n  sum(rate(http_request_duration_seconds_count{handler=\"v1/data\", method=\"post\"}[$__rate_interval]))\n) * 100"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}