version: '3'
services:
  ghnotify:
    image: ghcr.io/m-mizutani/ghnotify:v0.1.3
    command:
      - --remote-url
      - http://opa_server:8181/v1/data/github/notify
      - serve
    env_file:
      - .env
    environment:
      - GHNOTIFY_ADDR=0.0.0.0:80
      - GHNOTIFY_LOG_LEVEL=debug
    ports:
      - 4080:80
    networks:
      - my_network

  opa_server:
    image: openpolicyagent/opa:latest
    command:
      - run
      - --server
      - --addr
      - :8181
      - --config-file
      - /config/opa-config.yml
      - --log-level
      - debug
    environment:
      - POLICY_SERVER_URL=http://policy_server:80
    ports:
      - 8181:8181
    networks:
      - my_network
    volumes:
      - ./opa-config.yml:/config/opa-config.yml

  policy_server:
    image: nginx:stable-alpine
    volumes:
      - ./bundle.tar.gz:/app/policies/bundle.tar.gz
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5080:80
    networks:
      - my_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: always
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
    networks:
      - my_network
    command:
      - --docker_only
      - --housekeeping_interval=5s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - my_network
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: adminpass
      GF_SECURITY_ADMIN_USER: admin
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json

networks:
  my_network:
